name: notif
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0-28.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  awesome_notifications: ^0.7.4+1
  awesome_notifications_fcm: ^0.7.4+1
  firebase_messaging: ^14.6.2
  firebase_core: ^2.13.1
  cupertino_icons: ^1.0.5
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
